### ISSUE TITLE
JAVA- Clase Monitor

### ISSUE THREAD

**Issue by CMCNY** [CodeSystem2022/JavaDabaDevs-3Semestre#10]
Subir el archivo de java que se creo en la clase 1 llamada: **Monitor.java**

**Comment by SofiaAguirreZelay** [comment]
package ar.com.system2023.mundopc;

public class Monitor {
    private final int idMonitor;
    private String marca;
    private double tamanio;
    private static int contadorMonitores;
    
    private Monitor{} {
    this.idMonitor = ++Monitor.contadorMonitores;  
}
    
 public Monitor{String marca, double tamanio){
     this(); //Llamado al constructor vacio
     this.marca = marca;
     this.tamanio = tamanio;
 }
 
public String getMarca() {
        return this.marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }

    public double getTamanio() {
        return this.tamanio;
    }

    public void setTamanio(double tamanio) {
        this.tamanio = tamanio;
    }
    //Ingresamos manualmente el getidMonitor
    public int getIdMonitor() {
        return this.idMonitor;
    }

    @Override
    public String toString() {
        return "Monitor{" + "idMonitor=" + idMonitor + ", marca=" + marca + ", tamanio=" + tamanio + '}';
    }
    
}
