### ISSUE TITLE
JS- PruebaPersonas.js, Clase9, TSLeccion07

### ISSUE THREAD

**Issue by CMCNY** [CodeSystem2022/JavaDabaDevs-3Semestre#141]
Realizar la clase 9 de JavaScript.
Subir archivo de la carperta TSLeccion07:
- PruebaPersonas.js
https://drive.google.com/file/d/1VGrMYdEbb7w9sXpXpjKEWUdCf16DOZa9/view?usp=drive_link

**Comment by AraceliPintos** [comment]
se subió archivo prueba persona.js en TSLeccion07
