### ISSUE TITLE
JAVA - Argumentos variables - Video 1

### ISSUE THREAD

**Issue by Augustonc** [CodeSystem2022/JavaDabaDevs-3Semestre#31]
_Si sos miembro del canal de telegram podés ver el video en el siguiente Link_
[https://t.me/c/1521327392/13120/14062](url)

**Descripción General**

1. En NetBeans crear un nuevo proyecto llamado ArgumentosVariable
3. Guardardarlo en la carpeta Lección02
4. Crear la clase TestArgumentosVariable
5. Seguir las instrucciones del Profesor

**Comment by pilochincho** [comment]
Hecho
